### ISSUE TITLE
Webpack 5 doesn't work

### ISSUE THREAD

**Issue by solidevolution** [nuxt-modules/storybook#386]
### Version
@nuxtjs/storybook: 4.3.1
nuxt: v2.15.8

### Steps to reproduce
Set default setup for this versions to core builder "webpack5" and install the dependencies

```
npm install @storybook/builder-webpack5 @storybook/manager-webpack5 --save-dev
```

### What is Expected?

Storybook works with webpack5

### What is actually happening?

```
 Preparing project for development                                                                                          17:55:25
ℹ Initial build may take a while                                                                                             17:55:25
ℹ Discovered Components: .nuxt-storybook/components/readme.md                                                                17:55:25
✔ Builder initialized                                                                                                        17:55:25
✔ Nuxt files generated                                                                                                       17:55:25
ℹ Waiting for file changes                                                                                                   17:55:25
info @nuxtjs/storybook v4.3.1
info
info => Loading presets
info => Serving static files from /path/static at /
info => Loading custom manager config
info => Using PostCSS preset with postcss@8.4.13
info => Using default Webpack5 setup
info => Loading custom manager config
<i> [webpack-dev-middleware] wait until bundle finished
/Users/solidevolution/Entwicklung/bellicon-ui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/rules/RuleSetCompiler.js:373
		return new Error(
         ^
Error: Compiling RuleSet failed: Unexpected property test in condition (at ruleSet[1].rules[1].resource.test: resource => {
        currentResource = resource
        return true
      })
    at RuleSetCompiler.error (/Users/solidevolution/Entwicklung/bellicon-ui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/rules/RuleSetCompiler.js:373:10)
    at RuleSetCompiler.compileCondition (/Users/solidevolution/Entwicklung/bellicon-ui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/rules/RuleSetCompiler.js:309:17)
    at /Users/solidevolution/Entwicklung/bellicon-ui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/rules/BasicMatcherRulePlugin.js:29:40
    at Hook.eval (eval at create (/Users/solidevolution/Entwicklung/bellicon-ui/node_modules/@storybook/builder-webpack5/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:19:1)
    at RuleSetCompiler.compileRule (/Users/solidevolution/Entwicklung/bellicon-ui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/rules/RuleSetCompiler.js:177:19)
    at /Users/solidevolution/Entwicklung/bellicon-ui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/rules/RuleSetCompiler.js:154:9
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (/Users/solidevolution/Entwicklung/bellicon-ui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/rules/RuleSetCompiler.js:153:16)
    at RuleSetCompiler.compileRule (/Users/solidevolution/Entwicklung/bellicon-ui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/rules/RuleSetCompiler.js:184:30)
    at /Users/solidevolution/Entwicklung/bellicon-ui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/rules/RuleSetCompiler.js:154:9
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (/Users/solidevolution/Entwicklung/bellicon-ui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/rules/RuleSetCompiler.js:153:16)
    at RuleSetCompiler.compile (/Users/solidevolution/Entwicklung/bellicon-ui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/rules/RuleSetCompiler.js:68:22)
    at new NormalModuleFactory (/Users/solidevolution/Entwicklung/bellicon-ui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:237:34)
    at Compiler.createNormalModuleFactory (/Users/solidevolution/Entwicklung/bellicon-ui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/Compiler.js:1128:31)
    at Compiler.newCompilationParams (/Users/solidevolution/Entwicklung/bellicon-ui/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/Compiler.js:1149:30)

 FATAL  Failed to run command nuxt-storybook:                                                                                17:55:25
Error: Command failed with exit code 1: nuxt-storybook


   ╭────────────────────────────────────────────────────────────╮
   │                                                            │
   │   ✖ Nuxt Fatal Error                                       │
   │                                                            │
   │   Failed to run command `nuxt-storybook`:                  │
   │   Error: Command failed with exit code 1: nuxt-storybook   │
   │                                                            │
   ╰────────────────────────────────────────────────────────────╯
```

**Comment by farnabaz** [comment]
Nuxt storybook is not compatible with webpack5.
This is planned to future versions

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
