### ISSUE TITLE
Deploying Storybook on Github pages

### ISSUE THREAD

**Issue by bissolli** [nuxt-modules/storybook#390]
Is there a way to deploy the static version of Nuxt Storybook on Github pages?

I am halfway there but got stuck in a point where I believe it's very much related to nuxt context and ssr - as the storybook build are static files.

I used this package `crazy-max/ghaction-github-pages@v2` which is very simple and works pretty well with Storybook of simpler SPA projects.

With Nuxt Storybook it was deployed, it's accessible but I get this error in every story:

```
Unexpected token u in JSON at position 66
SyntaxError: Unexpected token u in JSON at position 66
    at JSON.parse (<anonymous>)
    at analytics_plugin (https://chatfood.github.io/chatfood-webview/main.ef27e837.iframe.bundle.js:1:106446)
    at _callee2$ (https://chatfood.github.io/chatfood-webview/main.ef27e837.iframe.bundle.js:1:335424)
    at tryCatch (https://chatfood.github.io/chatfood-webview/vendors~main.78a2bfd5.iframe.bundle.js:2:3982149)
    at Generator.invoke [as _invoke] (https://chatfood.github.io/chatfood-webview/vendors~main.78a2bfd5.iframe.bundle.js:2:3981772)
    at Generator.next (https://chatfood.github.io/chatfood-webview/vendors~main.78a2bfd5.iframe.bundle.js:2:3982915)
    at asyncGeneratorStep (https://chatfood.github.io/chatfood-webview/vendors~main.78a2bfd5.iframe.bundle.js:2:3305)
    at _next (https://chatfood.github.io/chatfood-webview/vendors~main.78a2bfd5.iframe.bundle.js:2:3607)
```

![image](https://user-images.githubusercontent.com/1808444/167076851-1244e93e-0a71-4c6b-a46d-fd431512b748.png)

**Comment by farnabaz** [comment]
Hey
Would you provide a reproduction project to the issue?

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
