### ISSUE TITLE
I recive an error on try run storybook

### ISSUE THREAD

**Issue by Takewi** [nuxt-modules/storybook#414]
Log of error
```bash
ERR! TypeError: The "id" argument must be of type string. Received an instance of Object
ERR!     at new NodeError (node:internal/errors:387:5)
ERR!     at validateString (node:internal/validators:162:11)
ERR!     at Module.require (node:internal/modules/cjs/loader:1050:3)
ERR!     at require (node:internal/modules/cjs/helpers:103:18)
ERR!     at interopRequireDefault (/home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:178:16)
ERR!     at getContent (/home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:194:10)
ERR!     at loadPreset (/home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:203:20)
ERR!     at /home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:255:18)
ERR!     at loadPreset (/home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:225:81)
ERR!     at /home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:255:18)
ERR!     at getPresets (/home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:313:23)
ERR!     at loadAllPresets (/home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:365:10)
ERR!     at buildDev (/home/gawi/ui-docs/node_modules/@storybook/core-server/dist/cjs/build-dev.js:209:50)
ERR!     at runMicrotasks (<anonymous>)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR!  TypeError: The "id" argument must be of type string. Received an instance of Object
ERR!     at new NodeError (node:internal/errors:387:5)
ERR!     at validateString (node:internal/validators:162:11)
ERR!     at Module.require (node:internal/modules/cjs/loader:1050:3)
ERR!     at require (node:internal/modules/cjs/helpers:103:18)
ERR!     at interopRequireDefault (/home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:178:16)
ERR!     at getContent (/home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:194:10)
ERR!     at loadPreset (/home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:203:20)
ERR!     at /home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:255:18)
ERR!     at loadPreset (/home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:225:81)
ERR!     at /home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:255:18)
ERR!     at getPresets (/home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:313:23)
ERR!     at loadAllPresets (/home/gawi/ui-docs/node_modules/@storybook/core-common/dist/cjs/presets.js:365:10)
ERR!     at buildDev (/home/gawi/ui-docs/node_modules/@storybook/core-server/dist/cjs/build-dev.js:209:50)
ERR!     at runMicrotasks (<anonymous>)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
ERR!   code: 'ERR_INVALID_ARG_TYPE'
ERR! }
```
That is my config in `nuxt.config.js`

```js
    storybook: {
        stories: ['~/stories/**/*.stories.js'],
        addons: ['@storybook/addon-actions', '@storybook/addon-links'],
    },
```
And project dependencies 
```json
    "dependencies": {
        "@nuxt/http": "^0.6.4",
        "@nuxtjs/i18n": "^7.3.0",
        "@nuxtjs/storybook": "^4.3.2",
        "chart.js": "3.9.1",
        "core-js": "^3.25.3",
        "dayjs": "^1.11.7",
        "nuxt": "^2.15.8",
        "nuxt-highlightjs": "^1.0.3",
        "vue": "^2.7.10",
        "vue-server-renderer": "^2.7.10",
        "vue-template-compiler": "^2.7.10",
        "vuetify": "^2.6.10"
    },
```

I don't know what's going on, I did a "clean" install but I get this error when trying to run the storybook.
Thanks in advance!

**Comment by tobiasdiez** [comment]
v4 of this module is no longer actively supported. Please try the newest version and open an new issue if the problem persists. Thank you for your understanding.
