### ISSUE TITLE
[8.0.0]Cannot read properties of undefined (reading '__STORYBOOK__')

### ISSUE THREAD

**Issue by baixiaoyu2997** [nuxt-modules/storybook#538]
error log:
```
=> Failed to build the preview
TypeError: Cannot read properties of undefined (reading '__STORYBOOK__')
    at setup (file:///Users/l.rain/Documents/workspace/deorderbook-monorepo/node_modules/.pnpm/@nuxtjs+storybook@8.0.0_@types+node@18.19.17_eslint@8.57.0_nuxt@3.11.1_react-dom@18.2.0_react_eelvpxrgnep26wtslernja6ivm/node_modules/@nuxtjs/storybook/dist/module.mjs:122:25)
    at normalizedModule (file:///Users/l.rain/Documents/workspace/deorderbook-monorepo/node_modules/.pnpm/@nuxt+kit@3.11.2_rollup@4.14.1/node_modules/@nuxt/kit/dist/index.mjs:2112:37)
    at async installModule (file:///Users/l.rain/Documents/workspace/deorderbook-monorepo/node_modules/.pnpm/@nuxt+kit@3.11.1_rollup@4.14.1/node_modules/@nuxt/kit/dist/index.mjs:2415:95)
    at async initNuxt (file:///Users/l.rain/Documents/workspace/deorderbook-monorepo/node_modules/.pnpm/nuxt@3.11.1_@types+node@18.19.17_@unocss+reset@0.59.0_eslint@8.57.0_floating-vue@5.2.2_rollup_g2d3cdn5gg3ikehhjhkd63jvqa/node_modules/nuxt/dist/index.mjs:4171:7)
    at async defineNuxtConfig (/Users/l.rain/Documents/workspace/deorderbook-monorepo/node_modules/.pnpm/@storybook-vue+nuxt@0.2.6_@types+node@18.19.17_eslint@8.57.0_nuxt@3.11.1_react-dom@18.2.0_rea_iyoqj7mfen6vrnvfyql4jszn6u/node_modules/@storybook-vue/nuxt/dist/preset.cjs:6744:3)
    at async Object.viteFinal (/Users/l.rain/Documents/workspace/deorderbook-monorepo/node_modules/.pnpm/@storybook-vue+nuxt@0.2.6_@types+node@18.19.17_eslint@8.57.0_nuxt@3.11.1_react-dom@18.2.0_rea_iyoqj7mfen6vrnvfyql4jszn6u/node_modules/@storybook-vue/nuxt/dist/preset.cjs:6773:22)
    at async createViteServer (/Users/l.rain/Documents/workspace/deorderbook-monorepo/node_modules/.pnpm/@storybook+builder-vite@8.0.8_typescript@5.4.5_vite@5.2.8/node_modules/@storybook/builder-vite/dist/index.js:55:11505)
    at async Module.start (/Users/l.rain/Documents/workspace/deorderbook-monorepo/node_modules/.pnpm/@storybook+builder-vite@8.0.8_typescript@5.4.5_vite@5.2.8/node_modules/@storybook/builder-vite/dist/index.js:58:1102)
```

deps:
```
"devDependencies": {
    "@chromatic-com/storybook": "^1.3.3",
    "@nuxtjs/storybook": "^8.0.0",
    "@nuxt/kit": "^3.11.2",
    "@storybook-vue/nuxt": "^0.2.6",
    "@storybook/addon-essentials": "^8.0.8",
    "@storybook/addon-interactions": "^8.0.8",
    "@storybook/addon-links": "^8.0.8",
    "@storybook/blocks": "^8.0.8",
    "@storybook/builder-vite": "^8.0.8",
    "@types/fs-extra": "^11.0.4",
    "storybook": "^8.0.8",
    "storybook-addon-vue-slots": "^0.9.29"
  }
```

![image](https://github.com/nuxt-modules/storybook/assets/9149999/ef3bb90a-4d56-40bd-b5ea-8007e4f67cc5)

i think problem are here:
![image](https://github.com/nuxt-modules/storybook/assets/9149999/fd382c5a-2852-41db-81a5-2d9f59ecb133)

import.meta.env is static,  shouldn't change to `import.meta.env.__STORYBOOK__ = JSON.stringify( options )`, i guess

**Comment by 9mm** [comment]
I'm also getting this, and when i run this `npx storybook-nuxt init` in the docs it just reverts everything to v7

**Comment by jimmiejackson414** [comment]
^ Same. I know it's generally not kosher to follow up on closed issues, but I keep having to go into `node_modules/@nuxtjs/storybook/dist/module.mjs` to edit the `import.meta.env.__STORYBOOK__` issue, which prevents me from merging this branch up.

**Comment by tobiasdiez** [comment]
It's indeed not yet released. In the meantime, you can just use the github repo as the source for the `nuxtjs/storybook` dependency and it should work (https://pnpm.io/cli/add#install-from-git-repository).

**Comment by Paul-Hebert** [comment]
I'm having trouble using the GitHub repo as my import source. I ran the following command:

```zsh
npm i -D github:nuxt-modules/storybook
```

It ran successfully. My package.json was updated:

<img width="520" alt="image" src="https://github.com/nuxt-modules/storybook/assets/5798536/5bdf4fe0-6117-40d3-afcb-709ec7c9441b">

And I can see the package in `node_modules`:

<img width="462" alt="image" src="https://github.com/nuxt-modules/storybook/assets/5798536/3460b984-9cfc-4af1-ad48-e3e7f9fb122e">

However, I get an error when I try to run the app:

```
Cannot find module '/Users/paulhebert/repos/repo-name-redacted/@nuxtjs/storybook'
Require stack:
- /Users/paulhebert/repos/repo-name-redacted/index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
  at Function.resolve (node:internal/modules/helpers:136:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:251148)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:2210:29)
  at requireModule (node_modules/@nuxt/kit/dist/index.mjs:2215:24)
  at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2451:92)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2407:47)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:4023:7)
  at async NuxtDevServer._load (node_modules/nuxi/dist/chunks/dev2.mjs:6879:5)
  at async NuxtDevServer.load (node_modules/nuxi/dist/chunks/dev2.mjs:6811:7)
```

Any tips to get this working? I'll report back if I figure it out. Thanks!

**Comment by Paul-Hebert** [comment]
By the way, is there any timeline for releasing this fix? That would help me to know how to prioritize finding a workaround. Thanks!

**Comment by jimmiejackson414** [comment]
I'm still having this issue as well. I know all of these have been closed as duplicates, but would love to know when we might expect this very simple fix to be out.
Thanks for the otherwise great module and all the work put into it!

**Comment by tobiasdiez** [comment]
Sorry guys, we are still figuring out our release/development schedule. Stay tuned.

**Comment by bsiguret** [comment]
Hello @tobiasdiez ! I tried to install storybook for our nuxt3 app but I encountered this bug right away. Do you still not have any ETA on when you're going to merge the fix for it ? Thanks !

**Comment by tobiasdiez** [comment]
@chakAs3 could you please release a new version?

**Comment by Maxime-Asphalte** [comment]
Hello, 

When will it be released ? It's quite durty to get the direct repository and it forces me to use pnpm instead of bun...
