### ISSUE TITLE
Error when this storybook module is added to fresh Nuxt project

### ISSUE THREAD

**Issue by 1NF053C** [nuxt-modules/storybook#629]
Is this module compatible with **Nuxt 3**?

When I run `npm run dev`, I get:
```
 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading '__STORYBOOK__')                      8:30:53 PM
  at setup (node_modules/@nuxtjs/storybook/dist/module.mjs:122:25)
  at normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2112:37)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2415:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:4233:7)
  at async NuxtDevServer._load (node_modules/nuxi/dist/chunks/dev2.mjs:6879:5)
  at async NuxtDevServer.load (node_modules/nuxi/dist/chunks/dev2.mjs:6811:7)
  at async NuxtDevServer.init (node_modules/nuxi/dist/chunks/dev2.mjs:6806:5)
  at async Object.run (node_modules/nuxi/dist/chunks/dev-child.mjs:99:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1639:11)
 ```

I also get a type error in `nuxt.config.ts`
```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    '@nuxtjs/storybook',
  ],
  storybook: { // <-- Error, "storybook" is not a valid property for defineNuxtConfig param
     url: 'http://localhost:6006',
     storybookRoute: '/__storybook__',
     port: 6006,
  },
})
```

Does anyone have a minimal setup guide for adding to new nuxt project? (Minimal config, minimal installs, minimal steps)

**Comment by 1NF053C** [comment]
Solution:

Follow this setup guide: https://storybook.nuxtjs.org/getting-started/setup
And not this one: https://nuxt.com/modules/storybook

The former includes init script that adds .storybook/* files if they do not exist already.
