### ISSUE TITLE
ERROR  Internal server error: At least one <template> or <script> is required in a single file component.       

### ISSUE THREAD

**Issue by Ibochkarev** [nuxt-modules/storybook#638]
In https://github.com/nuxt-modules/storybook/releases/tag/v8.1.1 the error continues to block the use of Storybook

```bash
 ERROR  Internal server error: At least one <template> or <script> is required in a single file component.                                                                        2:26:19 PM
  Plugin: vite:vue
  File: /Users/ibochkarev/Projects/v3/src/widgets/templates/w-feed-template/w-video-section-template.vue
      at Object.parse$2 [as parse] (/Users/ibochkarev/Projects/v3/node_modules/.pnpm/@vue+compiler-sfc@3.4.21/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:1921:7)
      at createDescriptor (/Users/ibochkarev/Projects/v3/node_modules/.pnpm/@storybook-vue+nuxt@0.2.6_@types+node@18.19.31_encoding@0.1.13_eslint@8.57.0_meow@9.0.0_nuxt@_hv7zc5tdoxa7qtmqb6wsfxacpq/node_modules/@storybook-vue/nuxt/dist/preset.cjs:87:43)
      at transformMain (/Users/ibochkarev/Projects/v3/node_modules/.pnpm/@storybook-vue+nuxt@0.2.6_@types+node@18.19.31_encoding@0.1.13_eslint@8.57.0_meow@9.0.0_nuxt@_hv7zc5tdoxa7qtmqb6wsfxacpq/node_modules/@storybook-vue/nuxt/dist/preset.cjs:2380:34)
      at TransformContext.transform (/Users/ibochkarev/Projects/v3/node_modules/.pnpm/@storybook-vue+nuxt@0.2.6_@types+node@18.19.31_encoding@0.1.13_eslint@8.57.0_meow@9.0.0_nuxt@_hv7zc5tdoxa7qtmqb6wsfxacpq/node_modules/@storybook-vue/nuxt/dist/preset.cjs:2923:16)
      at Object.transform (file:///Users/ibochkarev/Projects/v3/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.31_sass@1.76.0_terser@5.30.3/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:51172:62)
      at async loadAndTransform (file:///Users/ibochkarev/Projects/v3/node_modules/.pnpm/vite@5.2.8_@types+node@18.19.31_sass@1.76.0_terser@5.30.3/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:53923:29)
```

https://github.com/storybook-vue/storybook-nuxt/issues/4#issuecomment-2156617807

**Comment by Ibochkarev** [comment]
@sbloska We don't use external libraries, the problem occurs with internal components.

And accordingly your solution is not suitable.

**Comment by tobiasdiez** [comment]
This should be fixed in the main branch, but requires a new release of the [packages/storybook-nuxt](https://github.com/nuxt-modules/storybook/tree/main/packages/storybook-nuxt) package. @chakAs3

**Comment by Ibochkarev** [comment]
@chakAs3 please help!

**Comment by Ibochkarev** [comment]
@tobiasdiez Hello! Please tell me how you can use the latest versions from Github without waiting for the release?

**Comment by Archetipo95** [comment]
@tobiasdiez this is still a problem in the current build

**Comment by tillsanders** [comment]
Hint: I realized that my problem with this was in fact caused by an issue with my own vite config.

**Comment by chakAs3** [comment]
@Archetipo95 @tillsanders  can you use the latest release 8.3.1 and let me know please.

**Comment by tillsanders** [comment]
It seems my issue was unrelated after all, so I cannot test this. Good luck!

**Comment by andreaswolf** [comment]
Still an error here with component folders where `global: true` is defined in nuxt.config.ts

**Comment by andreaswolf** [comment]
Update: the problem was that I still had my `vite.config.ts` lying around. After removing it and restarting Storybook, everything works fine so far.
