### ISSUE TITLE
Storybook starts with error "Converting circular structure to JSON"

### ISSUE THREAD

**Issue by prof-schnitzel** [nuxt-modules/storybook#817]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  NuxtUI
- Build Modules:    -

### Reproduction

https://github.com/prof-schnitzel/nuxt-storybook-bug

### Describe the bug

When using this module together with NuxtUI I get the error "Converting circular structure to JSON" during startup in dev mode. I debugged a bit and I found out that this is due to the plugin `vite:vue` which has a `devServer` configuration that is also using the plugin `vite:vue` that again has the `devServer` configuration and so on which causes this circular reference. You can reproduce this issue by simply running the command `npm run dev` in the provided reproduction repository.

**Comment by kilakewe** [comment]
+1

**Comment by BloodWorkXGaming** [comment]
Same here.

```
 ERROR  [unhandledRejection] Converting circular structure to JSON                                                                                                                                                                           14:29:28  

    at stringify (node_modules\.pnpm\json-stable-stringify@1.2.1\node_modules\json-stable-stringify\index.js:87:11)
    at stringify (node_modules\.pnpm\json-stable-stringify@1.2.1\node_modules\json-stable-stringify\index.js:99:17)
    at stringify (node_modules\.pnpm\json-stable-stringify@1.2.1\node_modules\json-stable-stringify\index.js:99:17)
    at stringify (node_modules\.pnpm\json-stable-stringify@1.2.1\node_modules\json-stable-stringify\index.js:99:17)
    at stringify (node_modules\.pnpm\json-stable-stringify@1.2.1\node_modules\json-stable-stringify\index.js:99:17)
    at stringify (node_modules\.pnpm\json-stable-stringify@1.2.1\node_modules\json-stable-stringify\index.js:99:17)
    at stringify (node_modules\.pnpm\json-stable-stringify@1.2.1\node_modules\json-stable-stringify\index.js:79:17)
    at stringify (node_modules\.pnpm\json-stable-stringify@1.2.1\node_modules\json-stable-stringify\index.js:99:17)
    at stableStringify (node_modules\.pnpm\json-stable-stringify@1.2.1\node_modules\json-stable-stringify\index.js:111:4)
    at Object.viteFinal (node_modules\.pnpm\@storybook-vue+nuxt@8.3.4-2_6e4aad9374cd3c015a55df48ea2a3ca4\node_modules\@storybook-vue\nuxt\dist\preset.cjs:3243:7)

ℹ Restarting Nuxt due to error: TypeError: Converting circular structure to JSON                                                                                                                                                 
```

in my case it happens when tailwindcss is installed with 
```
  css: ['~/assets/css/main.css'],
  vite: {
    plugins: [
      tailwindcss()
    ],
  },
```

commenting this out makes it work.

tested with version `8.3.4-29014119.3ac5114` and `8.3.3` of @nuxtjs/storybook.

Any workarounds or fixes?

**Comment by amora2972** [comment]
+1

**Comment by memic84** [comment]
+1

Same issue happens with tailwind

**Comment by domanhdat** [comment]
+1

**Comment by genu** [comment]
the issue is coming from the `json-stable-stringify` module. I don't think its able to handle well some nuxt configurations. I tried swapping it out with something like `flatted`, which does the same thing and the error goes away.

Its not exactly clear to me why we need to be stringifying all these configs (vite, nuxt, etc)

**Comment by tobiasdiez** [comment]
This is only to print the full vite config to the logs for easier debugging. I don't have a preference for which dependency to use. If flatted works well, we can use it. PR welcome.
